# Generated by Django 6.0.7 on 2026-07-20 01:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('resumen', models.CharField(help_text='Aparece en las tarjetas de listado y como meta descripción.', max_length=280)),
                ('contenido', models.TextField(help_text='Admite HTML básico (párrafos, negritas, enlaces, imágenes).')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='portadas/%Y/%m/')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=10)),
                ('destacado', models.BooleanField(default=False, help_text='Se muestra en la cabecera de portada.')),
                ('permite_anuncios', models.BooleanField(default=True, help_text='Desactívalo para artículos sin publicidad (ej. patrocinados aparte).')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='articulos.categoria')),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
